# Generated by Django 5.0.3 on 2024-03-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPUser',
            fields=[
                ('ip_address', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='IPProxyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('expiration', models.DateTimeField()),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip_auth.ipuser')),
            ],
        ),
    ]
