# Generated by Django 5.0.3 on 2024-03-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip_auth', '0003_rename_ipproxykey_ipsessions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IPSessions',
            new_name='IPSession',
        ),
    ]
