# Generated by Django 5.0.3 on 2024-03-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_auth', '0004_rename_ipsessions_ipsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipuser',
            name='token',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
